#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# general commands
mkdir -p /home/$USER/.config

# gitfiles
ln -sf ${BASEDIR}/gitconfig /home/$USER/.gitconfig
echo "git configuration step executed"

# ntp.br
bash ${BASEDIR}/ntp/install.sh
echo "ntp configuration step executed"

# vimfiles
ln -sf ${BASEDIR}/vim /home/$USER/.vim
vim +PluginInstall +qall
echo "vim configuration step executed"

# alacritty directory
rm -rf $HOME/.config/alacritty
ln -sf ${BASEDIR}/config/alacritty /home/$USER/.config/alacritty
echo "alacritty step executed"

# i3 directory
rm -rf $HOME/.config/i3
ln -sf ${BASEDIR}/config/i3 /home/$USER/.config/i3
echo "i3 step executed"

# polybar directory
rm -rf $HOME/.config/polybar
ln -sf ${BASEDIR}/config/polybar /home/$USER/.config/polybar
echo "polybar step executed"

# rofi directory
rm -rf $HOME/.config/rofi
ln -sf ${BASEDIR}/config/rofi /home/$USER/.config/rofi
echo "rofi step executed"

# user-dirs file 
ln -sf ${BASEDIR}/config/user-dirs.dirs /home/$USER/.config/user-dirs.dirs
echo "xdg step executed"

# zathura directory
rm -rf $HOME/.config/zathura
ln -sf ${BASEDIR}/config/zathura /home/$USER/.config/zathura
echo "zathura step executed"

# dunst directory
rm -rf $HOME/.config/dunst
ln -sf ${BASEDIR}/config/dunst /home/$USER/.config/dunst
echo "dunst step executed"

# local user share applications
mkdir -p /home/$USER/.local/share/
ln -sf ${BASEDIR}/local/share/applications /home/$USER/.local/share/applications
echo "local user share applications configuration step executed"

# tmux 
ln -sf ${BASEDIR}/tmux.conf /home/$USER/.tmux.conf
echo "tmux configuration step executed"

# vim directory
rm -rf $HOME/.config/vim
ln -sf ${BASEDIR}/vim /home/$USER/vim
echo "zathura step executed"

# xresources
ln -sf ${BASEDIR}/Xresources /home/$USER/.Xresources
echo "xresources configuration step executed"

# zsh - hardcoded user basedir !!! atention !!!
su - $USER -c 'bash /home/vitor/.dotfiles/zshrc/install.sh'
ln -sf ${BASEDIR}/zshrc/zshrc /home/$USER/.zshrc
echo "zsh configuration step executed"

# related to x250 thinkpad model
# configuration of trackpad
sudo ln -sf ${BASEDIR}/x250/70-synpatics.conf /etc/X11/xorg.conf.d/70-synaptics.conf
