#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# general commands
mkdir -p /home/$USER/.config

# gitfiles
ln -sf ${BASEDIR}/gitconfig /home/$USER/.gitconfig
echo "git configuration step executed"

# vimfiles
ln -sf ${BASEDIR}/vim /home/$USER/.vim
touch /home/$USER/.vim/projects.vim
vim +PlugInstall +qall
echo "vim configuration step executed"

# nvim
ln -sf ${BASEDIR}/config/nvim /home/$USER/.config/nvim
nvim +PackerInstall +qall
echo "nvim configuration step executed"

# alacritty directory
rm -rf $HOME/.config/alacritty
ln -sf ${BASEDIR}/config/alacritty /home/$USER/.config/alacritty
echo "alacritty step executed"

# zellij directory
rm -rf $HOME/.config/zellij
ln -sf ${BASEDIR}/config/zellij /home/$USER/.config/zellij
echo "zellij step executed"

# user-dirs file
ln -sf ${BASEDIR}/config/user-dirs.dirs /home/$USER/.config/user-dirs.dirs
echo "xdg step executed"

# local user share applications
mkdir -p /home/$USER/.local/share/
ln -sf ${BASEDIR}/local/share/applications /home/$USER/.local/share/applications
echo "local user share applications configuration step executed"

# xresources
ln -sf ${BASEDIR}/Xresources /home/$USER/.Xresources
echo "xresources configuration step executed"

# zsh - hardcoded user basedir !!! atention !!!
su - $USER -c 'bash /home/vitor/.dotfiles/zshrc/install.sh'
ln -sf ${BASEDIR}/zshrc/zshrc /home/$USER/.zshrc
echo "zsh configuration step executed"

# starship
ln -sf ${BASEDIR}/config/starship.toml /home/$USER/.config/starship.toml
echo "starship step executed"
