"Charset Config"
scriptencoding utf-8
set encoding=utf-8
set nocompatible
filetype off

"Source files"
source ~/.vim/plug.vim
source ~/.vim/projects.vim

"netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 20

augroup ProjectDrawer
  autocmd!
  autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'Vexplore' argv()[0] | wincmd p | ene | endif
augroup END

map <silent> ff :Lexplore<CR>

"Quickfix searches
map qf :copen<cr>

"General Config"
syntax on
set number
set backspace=indent,eol,start
set showmode
set nowrap
set hlsearch
set laststatus=2
filetype plugin on
set noerrorbells visualbell t_vb=

"General maps
map fz :FZF<cr>
nnoremap qq <C-w>w

"Turn Off Swap Files"
set noswapfile
set nobackup
set nowb

"Tex options"
let g:tex_flavor = 'tex'
let maplocalleader = "\\"

"Indentation Config"
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set showmatch

"Scrolling Config"
set scrolloff=8
set sidescrolloff=15
set sidescroll=1

"Changing make options"
augroup auto_make
    autocmd!
    "autocmd BufWritePost * silent make
    autocmd QuickFixCmdPost *make* cwindow
augroup END

