# Path to your oh-my-zsh installation.
export ZSH=/home/$USER/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="daveverwer"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Loading plugins
plugins=(git git-flow httpie kubectl poetry)

# User configuration
source $ZSH/oh-my-zsh.sh > /dev/null 2>&1
# env vars
source ~/.dotfiles/env/env.sh > /dev/null 2>&1
# aliases
source ~/.dotfiles/alias/alias.sh > /dev/null 2>&1

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
