# Path to your oh-my-zsh installation.
export ZSH=/home/$USER/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="daveverwer"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
#ENABLE_CORRECTION="true"

# Loading plugins
plugins=(git git-flow httpie docker kubectl poetry tmux ansible ssh-agent)

# ssh-agent configuration
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa hivelocity_id_rsa ifce_id_rsa
zstyle :omz:plugins:ssh-agent lifetime 8h

# User configuration
source $ZSH/oh-my-zsh.sh > /dev/null 2>&1
# env vars
source ~/.dotfiles/env/env.sh > /dev/null 2>&1
# aliases
source ~/.dotfiles/alias/alias.sh > /dev/null 2>&1

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="$PATH:$HOME/.local/bin"

# Add gopath to another place
export GOPATH=$HOME/.go

autoload -U +X bashcompinit && bashcompinit
# complete -o nospace -C /usr/bin/vault vault
# complete -o nospace -C /usr/bin/terraform terraform

# npm stuff
# npm set prefix ~/.npm
# PATH="$HOME/.npm/bin:$PATH"""
# PATH="./node_modules/.bin:$PATH"""
eval "$(starship init zsh)"
