add_newline = false
format = """
$username\
$hostname\
$directory\
$python\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""

right_format = """
$terraform
"""

[fill]
symbol = " "

[username]
show_always = true

[directory]
truncation_length = 8
truncation_symbol = "../"
read_only = " 🔒"

[git_metrics]
disabled = true
added_style = "green"
deleted_style = "red"
format = '\(([+$added]($added_style))/([-$deleted]($deleted_style))\) '

[terraform]
format = '[$workspace]($style) \([$version]($style)\)'

#[gcloud]
#format = '[$active ☁️ \($project\)]($style) '

#[aws]
#format = '[$profile ☁️ \($region\)]($style) '
