
[theme]
name = "plain"

[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#ffcccc"

separator = ""
separator_bg = "#282A36"
separator_fg = ""

good_bg = "#50FA7B"
good_fg = "#000000"
info_bg = "#282A36"

warning_bg = "#FF5555"
warning_fg = "#FFFFFF"

critical_bg = "#FF5555"
critical_fg = "#F8F8F2"

[[block]]
block = "net"
device = "enp0s25"
format = "{ip} {speed_down} {speed_up}"
hide_inactive = true

[[block]]
block = "net"
device = "wlp3s0"
format = "{ipv6}"
hide_inactive = true

[[block]]
block = "net"
device = "wlp3s0"
format = "{ip} {speed_down} {speed_up}"
hide_inactive = true

[[block]]
block = "net"
device = "tun0"
format = "{ip}"
hide_inactive = true

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "sound"

[[block]]
block = "battery"
device = "BAT0"
format = "{percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
on_click = "gsimplecal"
