
[theme]
name = "plain"

[theme.overrides]
idle_bg = "#282A36"
idle_fg = "#ffcccc"

separator = ""
separator_bg = "#282A36"
separator_fg = ""

good_bg = "#50FA7B"
good_fg = "#000000"
info_bg = "#282A36"

warning_bg = "#FF5555"
warning_fg = "#FFFFFF"

critical_bg = "#FF5555"
critical_fg = "#F8F8F2"

[[block]]
block = "bluetooth"
mac = "B0:18:6F:0C:14:3B"
label = " JVC Azul"

[[block]]
block = "bluetooth"
mac = "DC:2C:26:28:64:1B"
label = " Keyboard K2"

[[block]]
block = "bluetooth"
mac = "EC:4C:47:F9:9F:CD"
label = " XT91"

[[block]]
block = "bluetooth"
mac = "00:14:41:0C:0A:0F"
label = " JVC"

[[block]]
block = "bluetooth"
mac = "0C:A6:94:FC:18:49"
label = " JBL GO"

[[block]]
block = "watson"
show_time = true

[[block]]
block = "speedtest"
interval = 1800

[[block]]
block = "uptime"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min} min, {max} max, {average} avg"
chip = "*-isa-*"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"
